/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the GitHub repository.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DevicePluginSwitcherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MODE_BOTH = "both";
var MODE_DESKTOP = "desktop";
var MODE_MOBILE = "mobile";
var MODE_DISABLED = "disabled";
var SVG_NS = "http://www.w3.org/2000/svg";
function createSvgElement(tagName, attrs) {
  const element = document.createElementNS(SVG_NS, tagName);
  for (const [key, value] of Object.entries(attrs)) {
    element.setAttribute(key, value);
  }
  return element;
}
function appendSvgElement(parent, tagName, attrs) {
  const element = createSvgElement(tagName, attrs);
  parent.appendChild(element);
  return element;
}
function createBrandLogoSvg() {
  const svg = createSvgElement("svg", {
    xmlns: SVG_NS,
    viewBox: "0 0 256 256",
    role: "img",
    "aria-label": "Device Extensions Switcher logo"
  });
  appendSvgElement(svg, "circle", {
    cx: "128",
    cy: "128",
    r: "120",
    fill: "none",
    stroke: "#000",
    "stroke-width": "6"
  });
  appendSvgElement(svg, "path", {
    d: "m128 8a120 120 0 0 0 0 240 60 60 0 0 1 0-120 60 60 0 0 0 0-120z",
    fill: "#fff"
  });
  appendSvgElement(svg, "path", {
    d: "m128 8a120 120 0 0 1 0 240 60 60 0 0 1 0-120 60 60 0 0 0 0-120z"
  });
  appendSvgElement(svg, "rect", {
    x: "70",
    y: "50",
    width: "60",
    height: "40",
    rx: "4"
  });
  appendSvgElement(svg, "rect", {
    x: "95",
    y: "92",
    width: "10",
    height: "8"
  });
  appendSvgElement(svg, "rect", {
    x: "140",
    y: "150",
    width: "36",
    height: "60",
    rx: "6",
    fill: "#fff",
    stroke: "#000",
    "stroke-width": "2"
  });
  appendSvgElement(svg, "circle", {
    cx: "158",
    cy: "204",
    r: "3"
  });
  return svg;
}
var DEFAULT_SETTINGS = {
  version: 3,
  assignments: {},
  protectedPluginIds: ["device-plugin-switcher"],
  applyMode: "session",
  autoApplyOnStartup: true,
  applyDelayMs: 1500,
  sortBy: "name"
};
function isAssignmentMode(value) {
  return value === MODE_BOTH || value === MODE_DESKTOP || value === MODE_MOBILE || value === MODE_DISABLED;
}
var DevicePluginSwitcherPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    await this.initializeMissingAssignments(true);
    this.addSettingTab(new DevicePluginSwitcherSettingTab(this.app, this));
    this.addCommand({
      id: "apply-current-device-state",
      name: "Apply current device state",
      callback: () => {
        void this.applyDeviceState({ manual: true });
      }
    });
    this.addCommand({
      id: "open-options",
      name: "Open options",
      callback: () => {
        var _a, _b;
        const appWithSetting = this.app;
        (_b = (_a = appWithSetting.setting) == null ? void 0 : _a.openTabById) == null ? void 0 : _b.call(_a, this.manifest.id);
      }
    });
    if (this.settings.autoApplyOnStartup) {
      const delay = Number(this.settings.applyDelayMs || 1500);
      const timeout = window.setTimeout(() => {
        void this.applyDeviceState({ manual: false });
      }, delay);
      this.register(() => window.clearTimeout(timeout));
    }
  }
  async loadSettings() {
    var _a;
    const loaded = await this.loadData();
    const safeLoaded = loaded || {};
    const selfId = ((_a = this.manifest) == null ? void 0 : _a.id) || "device-plugin-switcher";
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...safeLoaded,
      assignments: {
        ...DEFAULT_SETTINGS.assignments,
        ...safeLoaded.assignments || {}
      },
      // Hidden defaults: keep the plugin simple and safe for synced configuration setups.
      applyMode: "session",
      autoApplyOnStartup: true,
      applyDelayMs: 1500,
      protectedPluginIds: [selfId]
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getDeviceLabel() {
    if (import_obsidian.Platform.isMobile) return "mobile";
    if (import_obsidian.Platform.isDesktop) return "desktop";
    return "unknown";
  }
  getPluginManager() {
    return this.app.plugins;
  }
  getInstalledPlugins() {
    var _a;
    const manager = this.getPluginManager();
    const manifests = (manager == null ? void 0 : manager.manifests) || {};
    const values = manifests instanceof Map ? Array.from(manifests.values()) : Object.values(manifests);
    const selfId = ((_a = this.manifest) == null ? void 0 : _a.id) || "device-plugin-switcher";
    const rows = values.filter((manifest) => Boolean(manifest == null ? void 0 : manifest.id) && manifest.id !== selfId).map((manifest) => ({
      id: manifest.id,
      name: manifest.name || manifest.id,
      version: manifest.version || "",
      description: manifest.description || "",
      isDesktopOnly: Boolean(manifest.isDesktopOnly),
      enabled: this.isPluginEnabled(manifest.id),
      protected: this.isProtectedPlugin(manifest.id)
    }));
    const sortBy = this.settings.sortBy || "name";
    rows.sort((a, b) => {
      if (sortBy === "id") return a.id.localeCompare(b.id);
      if (sortBy === "status") return Number(b.enabled) - Number(a.enabled) || a.name.localeCompare(b.name);
      return a.name.localeCompare(b.name);
    });
    return rows;
  }
  isPluginEnabled(pluginId) {
    var _a;
    const manager = this.getPluginManager();
    if ((_a = manager == null ? void 0 : manager.enabledPlugins) == null ? void 0 : _a.has(pluginId)) return true;
    if ((manager == null ? void 0 : manager.plugins) && Object.prototype.hasOwnProperty.call(manager.plugins, pluginId)) return true;
    return false;
  }
  isProtectedPlugin(pluginId) {
    var _a;
    const protectedIds = new Set(this.settings.protectedPluginIds || []);
    protectedIds.add(((_a = this.manifest) == null ? void 0 : _a.id) || "device-plugin-switcher");
    return protectedIds.has(pluginId);
  }
  getAssignment(plugin) {
    var _a;
    const existing = (_a = this.settings.assignments) == null ? void 0 : _a[plugin.id];
    if (isAssignmentMode(existing)) return existing;
    if (plugin.isDesktopOnly) return MODE_DESKTOP;
    return plugin.enabled ? MODE_BOTH : MODE_DISABLED;
  }
  async initializeMissingAssignments(save) {
    var _a;
    const plugins = this.getInstalledPlugins();
    let changed = false;
    for (const plugin of plugins) {
      if (!this.settings.assignments[plugin.id]) {
        this.settings.assignments[plugin.id] = this.getAssignment(plugin);
        changed = true;
      }
    }
    const selfId = ((_a = this.manifest) == null ? void 0 : _a.id) || "device-plugin-switcher";
    if (!this.settings.protectedPluginIds.includes(selfId)) {
      this.settings.protectedPluginIds.push(selfId);
      changed = true;
    }
    this.settings.assignments[selfId] = MODE_BOTH;
    if (changed && save) await this.saveSettings();
  }
  getDesiredEnabledSet() {
    const desired = /* @__PURE__ */ new Set();
    const plugins = this.getInstalledPlugins();
    const isMobile = import_obsidian.Platform.isMobile;
    const isDesktop = import_obsidian.Platform.isDesktop;
    for (const plugin of plugins) {
      const id = plugin.id;
      const mode = this.getAssignment(plugin);
      if (this.isProtectedPlugin(id)) {
        desired.add(id);
        continue;
      }
      if (plugin.isDesktopOnly && isMobile) continue;
      if (mode === MODE_BOTH) desired.add(id);
      else if (mode === MODE_DESKTOP && isDesktop) desired.add(id);
      else if (mode === MODE_MOBILE && isMobile) desired.add(id);
    }
    return desired;
  }
  getApplyPlan() {
    const desired = this.getDesiredEnabledSet();
    const plugins = this.getInstalledPlugins();
    const enable = [];
    const disable = [];
    const keep = [];
    for (const plugin of plugins) {
      if (desired.has(plugin.id)) {
        if (plugin.enabled) keep.push(plugin.id);
        else enable.push(plugin.id);
      } else if (plugin.enabled && !this.isProtectedPlugin(plugin.id)) {
        disable.push(plugin.id);
      }
    }
    return { desired, enable, disable, keep, plugins };
  }
  async enablePlugin(pluginId) {
    const manager = this.getPluginManager();
    if (this.isPluginEnabled(pluginId)) return;
    if (this.settings.applyMode === "persistent" && typeof (manager == null ? void 0 : manager.enablePluginAndSave) === "function") {
      await manager.enablePluginAndSave(pluginId);
      return;
    }
    if (typeof (manager == null ? void 0 : manager.enablePlugin) === "function") {
      await manager.enablePlugin(pluginId);
      if (this.settings.applyMode === "persistent" && typeof (manager == null ? void 0 : manager.saveEnabledPlugins) === "function") {
        await manager.saveEnabledPlugins();
      }
      return;
    }
    throw new Error("Obsidian plugin manager does not expose enablePlugin().");
  }
  async disablePlugin(pluginId) {
    const manager = this.getPluginManager();
    if (!this.isPluginEnabled(pluginId)) return;
    if (this.isProtectedPlugin(pluginId)) return;
    if (this.settings.applyMode === "persistent" && typeof (manager == null ? void 0 : manager.disablePluginAndSave) === "function") {
      await manager.disablePluginAndSave(pluginId);
      return;
    }
    if (typeof (manager == null ? void 0 : manager.disablePlugin) === "function") {
      await manager.disablePlugin(pluginId);
      if (this.settings.applyMode === "persistent" && typeof (manager == null ? void 0 : manager.saveEnabledPlugins) === "function") {
        await manager.saveEnabledPlugins();
      }
      return;
    }
    throw new Error("Obsidian plugin manager does not expose disablePlugin().");
  }
  async applyDeviceState({ manual } = { manual: false }) {
    await this.initializeMissingAssignments(true);
    const plan = this.getApplyPlan();
    const errors = [];
    for (const pluginId of plan.enable) {
      try {
        await this.enablePlugin(pluginId);
      } catch (error) {
        console.error(`[Device Extensions Switcher] Failed to enable ${pluginId}`, error);
        errors.push(`enable ${pluginId}: ${error instanceof Error ? error.message : String(error)}`);
      }
    }
    for (const pluginId of plan.disable) {
      try {
        await this.disablePlugin(pluginId);
      } catch (error) {
        console.error(`[Device Extensions Switcher] Failed to disable ${pluginId}`, error);
        errors.push(`disable ${pluginId}: ${error instanceof Error ? error.message : String(error)}`);
      }
    }
    if (manual || errors.length > 0) {
      const device = this.getDeviceLabel();
      if (errors.length > 0) {
        new import_obsidian.Notice(`Device Extensions Switcher: applied with ${errors.length} error(s). Check console.`);
      } else {
        new import_obsidian.Notice(`Device Extensions Switcher: ${device} device state applied. Enabled ${plan.enable.length}, disabled ${plan.disable.length}.`);
      }
    }
    return { plan, errors };
  }
  async setAssignment(pluginId, mode) {
    if (!isAssignmentMode(mode)) return;
    this.settings.assignments[pluginId] = mode;
    await this.saveSettings();
  }
  async resetAssignmentsFromCurrentState() {
    var _a;
    const plugins = this.getInstalledPlugins();
    this.settings.assignments = {};
    const selfId = ((_a = this.manifest) == null ? void 0 : _a.id) || "device-plugin-switcher";
    for (const plugin of plugins) {
      if (plugin.id === selfId) this.settings.assignments[plugin.id] = MODE_BOTH;
      else if (plugin.isDesktopOnly) this.settings.assignments[plugin.id] = plugin.enabled ? MODE_DESKTOP : MODE_DISABLED;
      else this.settings.assignments[plugin.id] = plugin.enabled ? MODE_BOTH : MODE_DISABLED;
    }
    await this.saveSettings();
  }
  async copyInstalledIdsToClipboard() {
    const plugins = this.getInstalledPlugins();
    const text = plugins.map((plugin) => `${plugin.id}    # ${plugin.name}`).join("\n");
    await navigator.clipboard.writeText(text);
    new import_obsidian.Notice("Installed plugin IDs copied to clipboard.");
  }
};
var DevicePluginSwitcherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.searchText = "";
    this.tableMount = null;
    this.plugin = plugin;
  }
  renderBrandHeader(containerEl) {
    const brand = containerEl.createDiv({ cls: "dps-brand" });
    const brandMedia = brand.createDiv({ cls: "dps-brand-media" });
    const logo = brandMedia.createDiv({ cls: "dps-brand-logo", attr: { "aria-hidden": "true" } });
    logo.appendChild(createBrandLogoSvg());
    const brandCopy = brand.createDiv({ cls: "dps-brand-copy" });
    brandCopy.createEl("div", { text: "Device Extensions Switcher", cls: "dps-brand-title" });
    brandCopy.createEl("div", { text: "Simply switch. Nothing else.", cls: "dps-brand-tagline" });
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("dps-settings");
    this.renderBrandHeader(containerEl);
    const device = this.plugin.getDeviceLabel();
    const intro = containerEl.createDiv({ cls: "dps-intro" });
    intro.createEl("p", {
      text: `Current device: ${device}. Choose where each installed community plugin should be active. Changes are applied immediately on this device.`
    });
    intro.createEl("p", {
      text: "Both = desktop and mobile. Desktop only = disabled on mobile. Mobile only = disabled on desktop. Disabled = disabled everywhere unless protected."
    });
    const syncNote = containerEl.createDiv({ cls: "dps-sync-note" });
    syncNote.createEl("strong", { text: "Sync prerequisite: " });
    syncNote.createEl("span", {
      text: "This extension does not sync data by itself. To use the same assignment table on desktop and mobile, sync your configuration and community extension data between devices."
    });
    new import_obsidian.Setting(containerEl).setName("Plugin assignment table").setHeading();
    new import_obsidian.Setting(containerEl).setName("Search plugins").setDesc("Filter by plugin name or ID.").addText((text) => {
      text.setPlaceholder("dataview, templater, git...").setValue(this.searchText).onChange((value) => {
        this.searchText = value.trim().toLowerCase();
        this.renderTable();
      });
    });
    this.tableMount = containerEl.createDiv({ cls: "dps-table-mount" });
    this.renderTable();
    new import_obsidian.Setting(containerEl).setName("Refresh plugin list").setDesc("Reload the installed plugin list without resetting your selected modes.").addButton((button) => {
      button.setButtonText("Refresh").onClick(() => {
        void (async () => {
          await this.plugin.initializeMissingAssignments(true);
          this.display();
        })();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Sort table by").setDesc("Controls the plugin table order.").addDropdown((dropdown) => {
      dropdown.addOption("name", "Name").addOption("id", "Plugin ID").addOption("status", "Current status").setValue(this.plugin.settings.sortBy || "name").onChange((value) => {
        void (async () => {
          this.plugin.settings.sortBy = value;
          await this.plugin.saveSettings();
          this.display();
        })();
      });
    });
  }
  renderTable() {
    if (!this.tableMount) return;
    this.tableMount.empty();
    const allPlugins = this.plugin.getInstalledPlugins();
    const query = this.searchText;
    const plugins = query ? allPlugins.filter((plugin) => plugin.name.toLowerCase().includes(query) || plugin.id.toLowerCase().includes(query)) : allPlugins;
    const summary = this.tableMount.createDiv({ cls: "dps-summary" });
    const counts = this.getCounts(allPlugins);
    summary.setText(`Installed: ${allPlugins.length} \xB7 Both: ${counts.both} \xB7 Desktop only: ${counts.desktop} \xB7 Mobile only: ${counts.mobile} \xB7 Disabled: ${counts.disabled}`);
    const isMobileUi = import_obsidian.Platform.isMobile;
    const wrapper = this.tableMount.createDiv({ cls: `dps-table-wrapper ${isMobileUi ? "dps-table-wrapper-mobile" : "dps-table-wrapper-desktop"}` });
    const table = wrapper.createEl("table", { cls: `dps-table ${isMobileUi ? "dps-table-mobile" : "dps-table-desktop"}` });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    const labels = isMobileUi ? ["Plugin", "Current", "Mode"] : ["Plugin", "Current", "Both", "Desktop only", "Mobile only", "Disabled"];
    labels.forEach((label) => {
      headerRow.createEl("th", { text: label });
    });
    const tbody = table.createEl("tbody");
    for (const plugin of plugins) {
      const row = tbody.createEl("tr");
      if (plugin.protected) row.addClass("dps-row-protected");
      if (!plugin.enabled) row.addClass("dps-row-disabled-now");
      const pluginCell = row.createEl("td", { cls: "dps-plugin-cell" });
      pluginCell.createEl("div", { text: plugin.name, cls: "dps-plugin-name" });
      pluginCell.createEl("div", { text: plugin.id, cls: "dps-plugin-id" });
      const badges = pluginCell.createDiv({ cls: "dps-badges" });
      if (plugin.version) badges.createSpan({ text: `v${plugin.version}`, cls: "dps-badge" });
      if (plugin.isDesktopOnly) badges.createSpan({ text: "desktop-only manifest", cls: "dps-badge dps-warning" });
      if (plugin.protected) badges.createSpan({ text: "protected", cls: "dps-badge dps-protected" });
      row.createEl("td", {
        text: plugin.enabled ? "Enabled" : "Disabled",
        cls: plugin.enabled ? "dps-current-enabled" : "dps-current-disabled"
      });
      if (isMobileUi) {
        this.addModeSelectCell(row, plugin);
      } else {
        this.addModeCell(row, plugin, MODE_BOTH);
        this.addModeCell(row, plugin, MODE_DESKTOP);
        this.addModeCell(row, plugin, MODE_MOBILE, plugin.isDesktopOnly);
        this.addModeCell(row, plugin, MODE_DISABLED);
      }
    }
    if (plugins.length === 0) {
      const empty = this.tableMount.createDiv({ cls: "dps-empty" });
      empty.setText("No plugins match the current search.");
    }
  }
  async changeAssignment(pluginId, mode) {
    await this.plugin.setAssignment(pluginId, mode);
    await this.plugin.applyDeviceState({ manual: false });
    this.renderTable();
  }
  addModeCell(row, plugin, mode, disabled = false) {
    const isSelected = this.plugin.getAssignment(plugin) === mode;
    const cell = row.createEl("td", {
      cls: `dps-mode-cell${disabled ? " dps-mode-cell-disabled" : ""}${isSelected ? " dps-mode-cell-selected" : ""}`
    });
    const input = cell.createEl("input", { type: "radio" });
    input.name = `dps-mode-${plugin.id}`;
    input.value = mode;
    input.checked = isSelected;
    input.disabled = disabled || plugin.protected && mode === MODE_DISABLED;
    input.addEventListener("change", () => {
      if (!input.checked) return;
      void this.changeAssignment(plugin.id, mode);
    });
  }
  addModeSelectCell(row, plugin) {
    const cell = row.createEl("td", { cls: "dps-mode-select-cell" });
    const select = cell.createEl("select", { cls: "dps-mode-select" });
    const options = [
      [MODE_BOTH, "Both"],
      [MODE_DESKTOP, "Desktop only"],
      [MODE_MOBILE, "Mobile only"],
      [MODE_DISABLED, "Disabled"]
    ];
    for (const [value, label] of options) {
      const option = select.createEl("option", { text: label, value });
      if (plugin.isDesktopOnly && value === MODE_MOBILE) {
        option.disabled = true;
      }
      if (plugin.protected && value === MODE_DISABLED) {
        option.disabled = true;
      }
    }
    select.value = this.plugin.getAssignment(plugin);
    select.addEventListener("change", () => {
      const mode = select.value;
      if (!isAssignmentMode(mode)) return;
      select.disabled = true;
      void this.changeAssignment(plugin.id, mode);
    });
  }
  getCounts(plugins) {
    const counts = { both: 0, desktop: 0, mobile: 0, disabled: 0 };
    for (const plugin of plugins) counts[this.plugin.getAssignment(plugin)] += 1;
    return counts;
  }
};

/* nosourcemap */